services:
    request:
        class: \Symfony\Component\HttpFoundation\Request
        factory: ['\Symfony\Component\HttpFoundation\Request', 'createFromGlobals']

    entity_manager:
        class: \Doctrine\ORM\EntityManager
        factory: ['\StoreApp\Infrastructure\EntityManagerFactory', 'getEntityManager']

    create_product_repository_db:
        class: \StoreApp\Infrastructure\Product\ProductRepositoryDB
        arguments: ['@entity_manager']

    create_product_use_case:
        class: \StoreApp\UseCase\CreateProduct\CreateProduct
        arguments: ['@create_product_repository_db']

    create_product_transformer:
        class: \StoreApp\Infrastructure\Product\Presentation\CreateProductTransformer

    create_product_controller:
        class: \StoreApp\Application\Api\ProductController
        arguments: ['@create_product_use_case', '@create_product_transformer']