create_product:
    path:     /product
    methods: [POST]
    defaults: {
        service: 'create_product_controller',
        method: 'createProduct',
        format: 'json'
      }

update_product:
    path:     /product/{od}
    methods: [POST]
    defaults: {
        service: 'update_product_controller',
        method: 'updateProduct',
        format: 'json'
      }

search_product:
    path:     /product
    methods: [GET]
    defaults: {
        service: 'search_product_controller',
        method: 'searchProduct',
        format: 'json'
      }

index_page:
    path: /
    methods: [GET]
    defaults: {
        service: 'index_controller',
        method: 'viewIndex',
        format: 'html'
      }