create_product:
    path:     /product
    methods: [POST]
    defaults: {
      service: 'create_product_controller',
      method: 'createProduct'
      }

search_product:
    path:     /product
    methods: [GET]
    defaults: {
      service: 'search_product_controller',
      method: 'searchProduct'
      }