route1:
    path:     /foo
    defaults: {
      class: '\StoreApp\Application\Api\ProductController',
      method: 'createProduct'
      }

route2:
    path:     /foo/bar
    defaults: { _controller: 'MyController::foobarAction' }