route1:
    path:     /foo
    defaults: {
      service: 'create_product_controller',
      method: 'createProduct'
      }

route2:
    path:     /foo/bar
    defaults: { _controller: 'MyController::foobarAction' }